BASE_APPS = (
        'wizardcms',
        'antymedia.antyadmin',
        'attachments',
        'announcements',
        'banners',
        'imageprocessor',
        'newsletter',
        'positions',
        'registry',
        'tabbedadmin',
        'django_widgets',
        'tabbedadmin',
        'chunks',
        )
